### ISSUE TITLE
Possibility to use pillars for more than salt-runners

### ISSUE THREAD

**Issue by rbjorklin** [jenkinsci/saltstack-plugin#32] opened 2016-06-22 11:44 UTC
Would it be possible to have the functionality implemented in #15 available for **local** and **local_batch** as well?

EDIT: I'm currently trying to pass in pillars as KWarguments: `pillar='{"data":{"organization": "{{ORGANIZATION_NAME}}", "jmx_enabled":"{{JMX_ENABLED}}","cluster":"{{CLUSTER_NAME}}","port_suffix":"{{PORT_SUFFIX}}","instance_hosts":"{{INSTANCE_HOSTS}}"}}'`

Unfortunately that does not work and I'm met with:

    Waiting for 1 minions
    1 minions are done
    Response on state.sls application.create-cluster for host.example.org:
    [{"host.example.org": "ERROR executing 'state.sls': Pillar data must be formatted as a dictionary, unless pillar_enc is specified."}]
    Finished: SUCCESS

EDIT2: This should probably not finish with `SUCCESS`

**Comment by rbjorklin** [comment] 2016-06-22 12:06
@mchugh19 what are your thoughts on this?

**Comment by mchugh19** [comment] 2016-06-22 17:08
Hey hey. Looks like we have a few things here:
1. You need to pass multiple pillar keys and values for local and local_batch
2. A pillar error was marked as a success
3. Request to unify the args and kwargs fields

So breaking this down:
1. Pillars should be functional for the local and local_batch. Something like `tests.pillar, "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}"` should work just fine. See issue #7 for any specifics. 
2. Should be properly handled as of 1.7.1 See issue #28 
3. On the roadmap for 2.0 :)   Since this would change the UI, it is deferred for a 'major' release.

Please let me know if you are having any troubles getting it going.

**Comment by ssoto2** [comment] 2016-06-27 19:25
Is it even possible to pass one variable when using local because i am getting a similar error to @rbjorklin just with one value. 

Testing from salt-master
`
salt -v 'Beta1_Redis1' state.sls ts.deploy.system.dev.config.test pillar='{"jar.settings":{"lookup":{"record_data_dump":{"groupid":"foobar"}}}}'
Executing job with jid 20160627150443880138
-------------------------------------------

Beta1_Redis1:
----------
          ID: test.test
    Function: cmd.run
        Name: echo test foobar
      Result: True
     Comment: Command "echo test foobar" run
     Started: 15:04:44.469024
    Duration: 5.737 ms
     Changes:   
              ----------
              pid:
                  2223
              retcode:
                  0
              stderr:
              stdout:
                  test foobar

Summary for Beta1_Redis1
------------
Succeeded: 1 (changed=1)

`

when testing from jenkins
`
Running jid: 20160627150919888241
Waiting for 1 minions
1 minions are done
Response on state.sls ts.deploy.system.dev.config.test for Beta1_Redis1*:
[{"Beta1_Redis1": "ERROR executing 'state.sls': Pillar data must be formatted as a dictionary, unless pillar_enc is specified."}]
Finished: SUCCESS
`

or am i just doing things wrong?  

Regards, 

S

**Comment by ssoto2** [comment] 2016-06-29 19:20
@mchugh19 I have reviewed the breakdown and issue #7 

The problem is that i can not replicate the sucessful portion that you mention

`
Jenkins Version: 1.652
Client Interface: local
Function: state.sls
Arguments: 'pillar='{"jar.settings":{"lookup":{"record_data_dump":{"groupid":"foobar"}}}}'
`

If you put the pillar in the following format (see below) you will not get an error
`
'pillar={"jar.settings":{"lookup":{"record_data_dump":{"groupid":"foobar"}}}}'
"pillar={"jar.settings":{"lookup":{"record_data_dump":{"groupid":"foobar"}}}}"
`

If the pillar is typed like the following (see below) it will fail
`
pillar='{"jar.settings":{"lookup":{"record_data_dump":{"groupid":"foobar"}}}}'
`

directly from the salt master no matter where the single all the single quote versions work
The major concern is now that the pillar is not being overriding the pillar in the state file.. 

When executing the following state:
`
{% set IPV4= "test" %}
{% set RECORD_GROUPID= salt['pillar.get']('jar.settings:lookup:record_data_dump:groupid') %}

test.test:
  cmd.run:
    - name: echo {{ IPV4 }} {{ RECORD_GROUPID }}
`

i would expect to get an echo with "test foobar", and when running directly from the salt master i do get "test foobar" but from the jenkin API the pillar does not override

**Comment by rbjorklin** [comment] 2016-10-13 13:35
Hey again looks like I forgot to reply here.  Your suggestion works for static values but I can't seem to use the `{{ variable }}` syntax that's supported for salt-runners. Do you have an example or is it not supported?

**Comment by mchugh19** [comment] 2016-10-17 11:25
Thanks for the report. So everything's file with the {{VAR}} syntax in your pillars?

**Comment by rbjorklin** [comment] 2016-10-18 07:44
Yup. This issue can probably be closed if new ones are created for the points you listed above.

**Closed** 2016-10-18 07:58 UTC
