### ISSUE TITLE
Question: SALTBUILDOUTPUT string format

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#27] opened 2016-04-19 10:42 UTC
I'm querying salt-mine for some data that I want to process later in groovy script step.
The resulting string in SALTBUILDOUTPUT in not a JSON, but rather a map converted into a string (single quotes). The logged query result (in jenkins job log) is JSON encoded though (double quotes).
Is this different by design (log format: JSON, buildoutput variable: not JSON) ?
Currently, to convert the result to JSON, I'm doing:
```
def jsonified = envVarsMap["SALTBUILDOUTPUT"].replaceAll( /'/, '"' )
```
in groovy script step.

**Comment by mchugh19** [comment] 2016-05-06 18:44
Good point. That was an oversight not by design. I'll get it corrected.

**Comment by mchugh19** [comment] 2016-05-06 19:03
Weird, I don't seem to have that issue. 

With a build job of cmd.run uptime, I can run a followup build step of `echo $SALTBUILDOUTPUT`
```
[{"web1":" 13:56:35 up 1:29, 1 user, load average: 0.00, 0.01, 0.01"}]
```
Which is valid json. 
I also tested with state.highstate output with the same results. 

Can you try a simple job, create a second "execute shell" buildstep with "echo $SALTBUILDOUTPUT"?

**Comment by mchugh19** [comment] 2016-08-04 06:27
Closing this out with no info. But if this comes up again, feel free to reopen.

**Closed by mchugh19** 2016-08-04 06:27 UTC
